# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: argoproj.gitops-promoter
PackageVersion: 0.45.0
PackageLocale: en-US
Publisher: argoproj
PackageName: gitops-promoter
License: Apache 2.0
ShortDescription: GitOps Promoter CLI
ManifestType: defaultLocale
ManifestVersion: 1.12.0
