# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: argoproj.gitops-promoter
PackageVersion: 0.45.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gitops-promoter.exe
  PortableCommandAlias: gitops-promoter
Installers:
- Architecture: arm64
  InstallerUrl: https://github.com/argoproj-labs/gitops-promoter/releases/download/v0.45.0/gitops-promoter_Windows_arm64.zip
  InstallerSha256: 8C2147DC2C7EAAE97A7BBB39A8235DFEBE2249049BB5627C4E0A9582783CF36F
- Architecture: x64
  InstallerUrl: https://github.com/argoproj-labs/gitops-promoter/releases/download/v0.45.0/gitops-promoter_Windows_x86_64.zip
  InstallerSha256: 20682096A12D68B063EC92D700B0DFD2DD963E09F1B7037F48BC8704D079973D
ManifestType: installer
ManifestVersion: 1.12.0
